// SPDX-License-Identifier: Zlib
//
// Copyright (c) 2026 Adrian "asie" Siekierka

#ifndef MOONSHL2_H__
#define MOONSHL2_H__

#include "common.h"
#include "ff.h"

#define MOONSHL2_EXTLINK_PATH "/moonshl2/extlink.dat"
#define MOONSHL2_RELOAD_PATH "/moonshl2/reload.dat"

// "EXT0"
#define MOONSHL2_EXTLINK_ID 0x30545845
#define MOONSHL2_EXTLINK_ID_LEN 16
#define MOONSHL2_EXTLINK_STRING_LEN 256
#define MOONSHL2_EXTLINK_STRING_COUNT 6
#define MOONSHL2_EXTLINK_ASCII_OFFSET(n) (MOONSHL2_EXTLINK_ID_LEN + ((n) * MOONSHL2_EXTLINK_STRING_LEN))
#define MOONSHL2_EXTLINK_UTF16_OFFSET(n) (MOONSHL2_EXTLINK_ID_LEN + (MOONSHL2_EXTLINK_STRING_COUNT * MOONSHL2_EXTLINK_STRING_LEN) + ((n) * MOONSHL2_EXTLINK_STRING_LEN * 2))

#define MOONSHL2_EXTLINK_FILE_PATH_ASCII_OFFSET MOONSHL2_EXTLINK_ASCII_OFFSET(0)
#define MOONSHL2_EXTLINK_FILE_DIR_ASCII_OFFSET  MOONSHL2_EXTLINK_ASCII_OFFSET(1)
#define MOONSHL2_EXTLINK_FILE_NAME_ASCII_OFFSET MOONSHL2_EXTLINK_ASCII_OFFSET(2)
#define MOONSHL2_EXTLINK_BOOT_PATH_ASCII_OFFSET MOONSHL2_EXTLINK_ASCII_OFFSET(3)
#define MOONSHL2_EXTLINK_BOOT_DIR_ASCII_OFFSET  MOONSHL2_EXTLINK_ASCII_OFFSET(4)
#define MOONSHL2_EXTLINK_BOOT_NAME_ASCII_OFFSET MOONSHL2_EXTLINK_ASCII_OFFSET(5)

#define MOONSHL2_EXTLINK_FILE_PATH_UTF16_OFFSET MOONSHL2_EXTLINK_UTF16_OFFSET(0)
#define MOONSHL2_EXTLINK_FILE_DIR_UTF16_OFFSET  MOONSHL2_EXTLINK_UTF16_OFFSET(1)
#define MOONSHL2_EXTLINK_FILE_NAME_UTF16_OFFSET MOONSHL2_EXTLINK_UTF16_OFFSET(2)
#define MOONSHL2_EXTLINK_BOOT_PATH_UTF16_OFFSET MOONSHL2_EXTLINK_UTF16_OFFSET(3)
#define MOONSHL2_EXTLINK_BOOT_DIR_UTF16_OFFSET  MOONSHL2_EXTLINK_UTF16_OFFSET(4)
#define MOONSHL2_EXTLINK_BOOT_NAME_UTF16_OFFSET MOONSHL2_EXTLINK_UTF16_OFFSET(5)

extern char executable_path[MOONSHL2_EXTLINK_STRING_LEN+1];

/**
 * @brief Initialize executable_path from extlink.dat.
 */
void moonshl2_init(FATFS *fs);

/**
 * @brief Build ARGV.
 */
void moonshl2_build_argv(void);

#endif /* MOONSHL2_H__ */
